/*
  Constants fot action types.
*/

export const NEW_SIGNUP = 'NEW_SIGNUP';
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const NEW_LOGIN = 'NEW_LOGIN';
export const GET_ALL_APPLICATION_NAMES = 'GET_ALL_APPLICATION_NAMES';
export const GET_ALL_ASSET_NAMES = 'GET_ALLL_ASSET_NAMES';
export const GET_APPLICATION_DATA = 'GET_APPLICATION_DATA';
export const GET_ASSET_DATA = 'GET_ASSET_DATA';
export const GET_CURRENT_ASSETS = 'GET_CURRENT_ASSETS';
export const GET_CURRENT_DEPENDENCIES = 'GET_CURRENT_DEPENDENCIES';
export const POST_APP_FORM = 'POST_APP_FORM';
export const POST_ASSET_OR_DEP = 'POST_ASSET_OR_DEP';
export const GET_ASSET_NAMES_TYPES = 'GET_ASSET_NAMES_TYPES';
