var obj = {
  all_ips: [],
  applications: [],
  asset_environment: 1,
  asset_function: "",
  asset_id: 0,
  asset_make: "",
  asset_model: "",
  asset_name: "",
  asset_type: 1,
  cluster_nodes: [],
  clustered: false,
  cpu: 0,
  data_center: "",
  db_asset_dependencies: [],
  db_dependency: "",
  disk_provisioned: "",
  disk_size: 0,
  dmz: false,
  domain_name: "",
  fileshare_dependencies: [],
  firewall: [],
  gateway: "",
  ip_address: "",
  is_blade: false,
  is_chassis: false,
  load_balanced: false,
  move_group: "",
  network_dependencies: [],
  notes: "",
  physical_or_virtual: "Physical",
  ram: 0,
  serial_number: 0,
  server_dependencies: [],
  storage_dependencies: [],
  subnet: "",
  time_stamp: "",
  vip_requirements: "",
  vlan: ""
};

export default obj;